const dictionaries = {
  en: {
    skip: 'Skip to content',
    services: 'Services',
    market: 'Saudi Market Entry',
    industries: 'Industries',
    cases: 'Case Studies',
    insights: 'Insights',
    about: 'About',
    consultation: 'Book a consultation',
    menu: 'Menu',
    close: 'Close menu',
    language: 'Choose language',
    emptyTitle: 'Content is being prepared',
    emptyBody: 'This section will appear after approved content is published.',
    readMore: 'Read more',
    all: 'All',
    search: 'Search insights',
    searchAction: 'Search',
    submit: 'Send request',
    sending: 'Sending…',
    success: 'Your request has been received.',
    error: 'We could not submit your request. Please try again.',
    required: 'Required',
    privacy: 'I agree to the privacy notice.',
    footer: 'GATEVIA',
    notFound: 'Page not found',
    home: 'Return home',
    whoFor: 'Who is this for',
    problems: 'Problems we solve',
    deliverables: 'What you get',
    process: 'How we work',
    benefits: 'Benefits',
    timeline: 'Timeline',
    relatedIndustries: 'Related industries',
    relatedCases: 'Related case studies',
    relatedInsights: 'Related insights',
    faqs: 'Frequently asked questions',
    context: 'Context',
    challenge: 'The challenge',
    objectives: 'Objectives',
    solution: 'Solution',
    results: 'Results',
    metrics: 'Metrics',
    servicesInvolved: 'Services involved',
    industryServices: 'Our services for this industry',
    industryInsights: 'Industry insights',
    readyMarket: 'Ready to enter the Saudi market?',
    interestedMarket: 'Interested in this market?',
    similarResults: 'Want similar results?',
    actInsights: 'Ready to act on these insights?',
    interestedPartnering: 'Interested in partnering?',
    visitWebsite: 'Visit website',
    demoContent: 'Demo content',
    illustrative: 'Illustrative',
    featuredCase: 'Featured case',
    confidentialClient: 'Confidential client',
    clients: 'Clients',
    partners: 'Partners',
    brands: 'Brands',
    productsVentures: 'Products & ventures',
    featuredIdentity: 'Featured identity',
    featuredStory: 'Featured story',
    viewAllCases: 'View all case studies',
    viewAllInsights: 'View all insights',
    viewEcosystem: 'View ecosystem',
    company: 'Company',
    resources: 'Resources',
    legal: 'Legal',
    contact: 'Contact',
    team: 'Team',
    partnerTypes: {
      strategic: 'Strategic',
      delivery: 'Delivery',
      technology: 'Technology',
      research: 'Research',
      government_ecosystem: 'Government / Ecosystem',
      other: 'Other',
    },
    productTypes: { product: 'Product', platform: 'Platform', venture: 'Venture' },
    launchStatuses: {
      concept: 'Concept',
      building: 'Building',
      active: 'Active',
      private_beta: 'Private beta',
      public: 'Public',
      paused: 'Paused',
      archived: 'Archived',
    },
    relationshipTypes: {
      owned: 'Owned',
      subsidiary: 'Subsidiary',
      managed: 'Managed',
      affiliate: 'Affiliate',
      investment: 'Investment',
      other: 'Other',
    },
    insightTypes: { article: 'Article', guide: 'Guide', report: 'Report' },
    privacyPolicy: 'Privacy policy',
    terms: 'Terms',
    cookies: 'Cookie policy',
  },
  'ar-SA': {
    skip: 'انتقل إلى المحتوى',
    services: 'الخدمات',
    market: 'دخول السوق السعودي',
    industries: 'القطاعات',
    cases: 'دراسات الحالة',
    insights: 'الرؤى',
    about: 'عن الشركة',
    consultation: 'احجز استشارة',
    menu: 'القائمة',
    close: 'إغلاق القائمة',
    language: 'اختر اللغة',
    emptyTitle: 'يجري إعداد المحتوى',
    emptyBody: 'سيظهر هذا القسم بعد نشر المحتوى المعتمد.',
    readMore: 'اقرأ المزيد',
    all: 'الكل',
    search: 'ابحث في الرؤى',
    searchAction: 'بحث',
    submit: 'إرسال الطلب',
    sending: 'جارٍ الإرسال…',
    success: 'تم استلام طلبك.',
    error: 'تعذر إرسال الطلب. حاول مرة أخرى.',
    required: 'مطلوب',
    privacy: 'أوافق على إشعار الخصوصية.',
    footer: 'GATEVIA',
    notFound: 'الصفحة غير موجودة',
    home: 'العودة للرئيسية',
    whoFor: 'لمن صُممت هذه الخدمة',
    problems: 'التحديات التي نعالجها',
    deliverables: 'ما الذي ستحصل عليه',
    process: 'كيف نعمل',
    benefits: 'الفوائد',
    timeline: 'الجدول الزمني',
    relatedIndustries: 'القطاعات ذات الصلة',
    relatedCases: 'دراسات الحالة ذات الصلة',
    relatedInsights: 'الرؤى ذات الصلة',
    faqs: 'الأسئلة الشائعة',
    context: 'السياق',
    challenge: 'التحدي',
    objectives: 'الأهداف',
    solution: 'الحل',
    results: 'النتائج',
    metrics: 'المؤشرات',
    servicesInvolved: 'الخدمات المقدمة',
    industryServices: 'خدماتنا لهذا القطاع',
    industryInsights: 'رؤى القطاع',
    readyMarket: 'هل أنت مستعد لدخول السوق السعودي؟',
    interestedMarket: 'مهتم بهذا السوق؟',
    similarResults: 'هل تريد نتائج مماثلة؟',
    actInsights: 'هل أنت مستعد للاستفادة من هذه الرؤى؟',
    interestedPartnering: 'مهتم بالشراكة؟',
    visitWebsite: 'زيارة الموقع',
    demoContent: 'محتوى تجريبي',
    illustrative: 'توضيحي',
    featuredCase: 'الحالة الرئيسية',
    confidentialClient: 'عميل سري',
    clients: 'العملاء',
    partners: 'الشركاء',
    brands: 'العلامات',
    productsVentures: 'المنتجات والمشاريع',
    featuredIdentity: 'هوية مميزة',
    featuredStory: 'الرؤية الرئيسية',
    viewAllCases: 'عرض جميع دراسات الحالة',
    viewAllInsights: 'عرض جميع الرؤى',
    viewEcosystem: 'استكشف المنظومة',
    company: 'الشركة',
    resources: 'المصادر',
    legal: 'قانوني',
    contact: 'التواصل',
    team: 'الفريق',
    partnerTypes: {
      strategic: 'استراتيجي',
      delivery: 'تنفيذ',
      technology: 'تقني',
      research: 'بحثي',
      government_ecosystem: 'حكومي / منظومة أعمال',
      other: 'أخرى',
    },
    productTypes: { product: 'منتج', platform: 'منصة', venture: 'مشروع' },
    launchStatuses: {
      concept: 'فكرة',
      building: 'قيد البناء',
      active: 'نشط',
      private_beta: 'تجربة خاصة',
      public: 'متاح',
      paused: 'متوقف مؤقتًا',
      archived: 'مؤرشف',
    },
    relationshipTypes: {
      owned: 'مملوك',
      subsidiary: 'شركة تابعة',
      managed: 'مُدار',
      affiliate: 'مرتبط',
      investment: 'استثمار',
      other: 'أخرى',
    },
    insightTypes: { article: 'مقال', guide: 'دليل', report: 'تقرير' },
    privacyPolicy: 'سياسة الخصوصية',
    terms: 'الشروط',
    cookies: 'سياسة ملفات الارتباط',
  },
} as const;
export type UiCopy = (typeof dictionaries)['en'];
export function copy(locale: string): UiCopy {
  return (
    locale.toLowerCase().startsWith('ar') ? dictionaries['ar-SA'] : dictionaries.en
  ) as UiCopy;
}
