const dictionaries = {
  en: {
    skip: 'Skip to content',
    services: 'Services',
    market: 'Saudi Market Entry',
    industries: 'Industries',
    cases: 'Case Studies',
    insights: 'Insights',
    about: 'About',
    consultation: 'Book a consultation',
    menu: 'Menu',
    close: 'Close menu',
    language: 'Choose language',
    emptyTitle: 'Content is being prepared',
    emptyBody: 'This section will appear after approved content is published.',
    readMore: 'Read more',
    all: 'All',
    search: 'Search insights',
    searchAction: 'Search',
    submit: 'Send request',
    sending: 'Sending…',
    success: 'Your request has been received.',
    error: 'We could not submit your request. Please try again.',
    required: 'Required',
    privacy: 'I agree to the privacy notice.',
    footer: 'GATEVIA',
    notFound: 'Page not found',
    home: 'Return home',
    whoFor: 'Who is this for',
    problems: 'Problems we solve',
    deliverables: 'What you get',
    process: 'How we work',
    benefits: 'Benefits',
    timeline: 'Timeline',
    relatedIndustries: 'Related industries',
    relatedCases: 'Related case studies',
    relatedInsights: 'Related insights',
    faqs: 'Frequently asked questions',
    context: 'Context',
    challenge: 'The challenge',
    objectives: 'Objectives',
    solution: 'Solution',
    results: 'Results',
    metrics: 'Metrics',
    servicesInvolved: 'Services involved',
    industryServices: 'Our services for this industry',
    industryInsights: 'Industry insights',
    readyMarket: 'Ready to enter the Saudi market?',
    interestedMarket: 'Interested in this market?',
    similarResults: 'Want similar results?',
    actInsights: 'Ready to act on these insights?',
    interestedPartnering: 'Interested in partnering?',
    visitWebsite: 'Visit website',
  },
  'ar-SA': {
    skip: 'انتقل إلى المحتوى',
    services: 'الخدمات',
    market: 'دخول السوق السعودي',
    industries: 'القطاعات',
    cases: 'دراسات الحالة',
    insights: 'الرؤى',
    about: 'عن الشركة',
    consultation: 'احجز استشارة',
    menu: 'القائمة',
    close: 'إغلاق القائمة',
    language: 'اختر اللغة',
    emptyTitle: 'يجري إعداد المحتوى',
    emptyBody: 'سيظهر هذا القسم بعد نشر المحتوى المعتمد.',
    readMore: 'اقرأ المزيد',
    all: 'الكل',
    search: 'ابحث في الرؤى',
    searchAction: 'بحث',
    submit: 'إرسال الطلب',
    sending: 'جارٍ الإرسال…',
    success: 'تم استلام طلبك.',
    error: 'تعذر إرسال الطلب. حاول مرة أخرى.',
    required: 'مطلوب',
    privacy: 'أوافق على إشعار الخصوصية.',
    footer: 'GATEVIA',
    notFound: 'الصفحة غير موجودة',
    home: 'العودة للرئيسية',
    whoFor: 'لمن صُممت هذه الخدمة',
    problems: 'التحديات التي نعالجها',
    deliverables: 'ما الذي ستحصل عليه',
    process: 'كيف نعمل',
    benefits: 'الفوائد',
    timeline: 'الجدول الزمني',
    relatedIndustries: 'القطاعات ذات الصلة',
    relatedCases: 'دراسات الحالة ذات الصلة',
    relatedInsights: 'الرؤى ذات الصلة',
    faqs: 'الأسئلة الشائعة',
    context: 'السياق',
    challenge: 'التحدي',
    objectives: 'الأهداف',
    solution: 'الحل',
    results: 'النتائج',
    metrics: 'المؤشرات',
    servicesInvolved: 'الخدمات المقدمة',
    industryServices: 'خدماتنا لهذا القطاع',
    industryInsights: 'رؤى القطاع',
    readyMarket: 'هل أنت مستعد لدخول السوق السعودي؟',
    interestedMarket: 'مهتم بهذا السوق؟',
    similarResults: 'هل تريد نتائج مماثلة؟',
    actInsights: 'هل أنت مستعد للاستفادة من هذه الرؤى؟',
    interestedPartnering: 'مهتم بالشراكة؟',
    visitWebsite: 'زيارة الموقع',
  },
} as const;
export type UiCopy = (typeof dictionaries)['en'];
export function copy(locale: string): UiCopy {
  return (
    locale.toLowerCase().startsWith('ar') ? dictionaries['ar-SA'] : dictionaries.en
  ) as UiCopy;
}
