import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class PublicContentService {
  constructor(private readonly prisma: PrismaService) {}
  languages() { return this.prisma.language.findMany({ where: { isActive: true }, orderBy: { sortOrder: 'asc' }, select: { code: true, name: true, nativeName: true, direction: true, isDefault: true } }); }
  async page(locale: string, slug: string) { const item = await this.prisma.page.findFirst({ where: { status: 'published', translations: { some: { locale, slug } } }, include: { translations: { where: { locale } }, sections: { where: { isVisible: true }, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { locale } } } } } }); if (!item) throw new NotFoundException('Page translation was not found.'); return item; }
  services(locale: string) { return this.prisma.service.findMany({ where: { status: 'published', translations: { some: { locale } } }, orderBy: [{ featured: 'desc' }, { sortOrder: 'asc' }], include: { translations: { where: { locale } }, category: { include: { translations: { where: { locale } } } } } }); }
  async service(locale: string, slug: string) { const item = await this.prisma.service.findFirst({ where: { status: 'published', translations: { some: { locale, slug } } }, include: { translations: { where: { locale } }, category: { include: { translations: { where: { locale } } } }, industries: { include: { industry: { include: { translations: { where: { locale } } } } } }, faqs: { include: { faq: { include: { translations: { where: { locale } } } } } } } }); if (!item) throw new NotFoundException('Service translation was not found.'); return item; }
  industries(locale: string) { return this.prisma.industry.findMany({ where: { status: 'published', translations: { some: { locale } } }, orderBy: [{ featured: 'desc' }, { sortOrder: 'asc' }], include: { translations: { where: { locale } } } }); }
  async industry(locale: string, slug: string) { const item = await this.prisma.industry.findFirst({ where: { status: 'published', translations: { some: { locale, slug } } }, include: { translations: { where: { locale } }, services: { include: { service: { include: { translations: { where: { locale } } } } } } } }); if (!item) throw new NotFoundException('Industry translation was not found.'); return item; }
  insights(locale: string, type?: 'article' | 'guide' | 'report', q?: string) { return this.prisma.insight.findMany({ where: { status: 'published', ...(type ? { type } : {}), translations: { some: { locale, ...(q ? { OR: [{ title: { contains: q, mode: 'insensitive' } }, { excerpt: { contains: q, mode: 'insensitive' } }] } : {}) } } }, orderBy: { publishedAt: 'desc' }, include: { translations: { where: { locale } }, category: { include: { translations: { where: { locale } } } } } }); }
  async insight(locale: string, slug: string) { const item = await this.prisma.insight.findFirst({ where: { status: 'published', translations: { some: { locale, slug } } }, include: { translations: { where: { locale } }, category: { include: { translations: { where: { locale } } } }, tags: { include: { tag: { include: { translations: { where: { locale } } } } } } } }); if (!item) throw new NotFoundException('Insight translation was not found.'); return item; }
  caseStudies(locale: string) { return this.prisma.caseStudy.findMany({ where: { status: 'published', translations: { some: { locale } } }, orderBy: [{ featured: 'desc' }, { publishedAt: 'desc' }], include: { translations: { where: { locale } } } }); }
  async caseStudy(locale: string, slug: string) { const item = await this.prisma.caseStudy.findFirst({ where: { status: 'published', translations: { some: { locale, slug } } }, include: { translations: { where: { locale } }, services: { include: { service: { include: { translations: { where: { locale } } } } } }, industries: { include: { industry: { include: { translations: { where: { locale } } } } } }, gallery: { include: { media: { include: { translations: { where: { locale } }, variants: true } } } } } }); if (!item) throw new NotFoundException('Case study translation was not found.'); return item; }
  team(locale: string) { return this.prisma.teamMember.findMany({ where: { status: 'published', translations: { some: { locale } } }, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { locale } } } }); }
  faqs(locale: string) { return this.prisma.faq.findMany({ where: { status: 'published', translations: { some: { locale } } }, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { locale } } } }); }
  settings() { return this.prisma.globalSetting.findMany({ where: { isPublic: true }, select: { key: true, value: true } }); }
  navigation(locale: string, key: string) { return this.prisma.navigationMenu.findFirst({ where: { key, status: 'published' }, include: { items: { where: { visible: true, parentId: null }, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { locale } }, children: { where: { visible: true }, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { locale } } } } } } } }); }
  trust(locale: string, kind: string) {
    const where = { status: 'published' as const, publicVisibility: true, translations: { some: { locale } } };
    switch (kind) { case 'clients': return this.prisma.client.findMany({ where, orderBy: [{ featured: 'desc' }, { sortOrder: 'asc' }], include: { translations: { where: { locale } } } }); case 'partners': return this.prisma.partner.findMany({ where, orderBy: [{ featured: 'desc' }, { sortOrder: 'asc' }], include: { translations: { where: { locale } } } }); case 'certifications': return this.prisma.certification.findMany({ where, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { locale } } } }); case 'trust-metrics': return this.prisma.trustMetric.findMany({ where, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { locale } } } }); default: throw new NotFoundException('Unknown trust resource.'); }
  }
  ecosystem(locale: string, kind: 'brands' | 'products') { const options = { where: { status: 'published' as const, translations: { some: { locale } } }, orderBy: [{ featured: 'desc' as const }, { sortOrder: 'asc' as const }], include: { translations: { where: { locale } } } }; return kind === 'brands' ? this.prisma.brand.findMany(options) : this.prisma.productVenture.findMany(options); }
  async ecosystemDetail(locale: string, kind: 'brands' | 'products', slug: string) { const options = { where: { status: 'published' as const, translations: { some: { locale, slug } } }, include: { translations: { where: { locale } }, industry: { include: { translations: { where: { locale } } } } } }; const item = kind === 'brands' ? await this.prisma.brand.findFirst(options) : await this.prisma.productVenture.findFirst(options); if (!item) throw new NotFoundException('Ecosystem translation was not found.'); return item; }
  testimonials(locale: string) { return this.prisma.testimonial.findMany({ where: { status: 'published', consentConfirmed: true, translations: { some: { locale } } }, orderBy: [{ featured: 'desc' }, { sortOrder: 'asc' }], include: { translations: { where: { locale } } } }); }
}
