import { BadRequestException, Body, Controller, Get, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { ApiCookieAuth, ApiTags } from '@nestjs/swagger';
import argon2 from 'argon2'; import { randomBytes, createHash } from 'node:crypto';
import { SessionGuard, PermissionGuard } from '../common/auth.guard'; import { CsrfGuard } from '../common/csrf.guard'; import { RequirePermissions } from '../common/permissions'; import type { GateviaRequest } from '../common/request-context'; import { PrismaService } from '../prisma/prisma.service'; import { QueueService } from '../queue/queue.service'; import { AuditService } from '../audit/audit.service';

@ApiTags('admin/identity') @ApiCookieAuth() @UseGuards(SessionGuard, CsrfGuard, PermissionGuard) @Controller('admin')
export class IdentityController {
  constructor(private readonly prisma:PrismaService,private readonly queues:QueueService,private readonly audit:AuditService){}
  @Get('users') @RequirePermissions('users.read') async users(@Query()query:{page?:string;pageSize?:string;q?:string;status?:string;sort?:string}) { const page=Math.max(1,Number(query.page)||1),pageSize=Math.min(100,Math.max(1,Number(query.pageSize)||20));const sortKey=query.sort?.replace(/^-/,'')==='updatedAt'?'updatedAt':'createdAt';const where={...(query.status?{status:query.status as 'active'|'suspended'|'invited'}:{}),...(query.q?{OR:[{email:{contains:query.q,mode:'insensitive' as const}},{displayName:{contains:query.q,mode:'insensitive' as const}}]}:{})}; const [data,total]=await this.prisma.$transaction([this.prisma.user.findMany({where,skip:(page-1)*pageSize,take:pageSize,orderBy:{[sortKey]:query.sort?.startsWith('-')?'desc':'asc'},select:{id:true,email:true,displayName:true,status:true,lastLoginAt:true,createdAt:true,updatedAt:true,roles:{include:{role:true}}}}),this.prisma.user.count({where})]);return{data,meta:{page,pageSize,total,pageCount:Math.ceil(total/pageSize)}}; }
  @Get('users/:id') @RequirePermissions('users.read') async getUser(@Param('id') id: string) { const user = await this.prisma.user.findUnique({ where: { id }, select: { id: true, email: true, displayName: true, status: true, roles: { include: { role: true } } } }); if (!user) throw new BadRequestException('User not found.'); return { data: { id: user.id, email: user.email, displayName: user.displayName, status: user.status, roles: user.roles.map(r => r.role) } }; }
  @Post('users') @RequirePermissions('users.manage') async createUser(@Body()body:{email:string;displayName:string;roleIds:string[]},@Req()req:GateviaRequest){const temporary=randomBytes(48).toString('base64url');const rawToken=randomBytes(32).toString('base64url');const passwordHash=await argon2.hash(temporary,{type:argon2.argon2id});const user=await this.prisma.$transaction(async(tx)=>{const created=await tx.user.create({data:{email:body.email.trim().toLowerCase(),displayName:body.displayName.trim(),passwordHash,status:'invited',mustChangePassword:true,roles:{create:body.roleIds.map(roleId=>({roleId}))}}});await tx.passwordResetToken.create({data:{userId:created.id,tokenHash:createHash('sha256').update(rawToken).digest('hex'),expiresAt:new Date(Date.now()+24*3600000)}});return created;});await this.queues.email.add('admin-invitation',{userId:user.id,token:rawToken});await this.audit.record({actorUserId:req.user!.id,action:'user.invited',entityType:'user',entityId:user.id,requestId:req.requestId});return{data:{id:user.id,email:user.email,status:user.status}}}
  @Patch('users/:id') @RequirePermissions('users.manage') async updateUser(@Param('id')id:string,@Body()body:{displayName?:string;status?:'active'|'suspended'|'invited';roleIds?:string[]},@Req()req:GateviaRequest){if(id===req.user!.id&&body.status==='suspended')throw new BadRequestException('You cannot suspend your current account.');const user=await this.prisma.$transaction(async(tx)=>{if(body.roleIds){await tx.userRole.deleteMany({where:{userId:id}});await tx.userRole.createMany({data:body.roleIds.map(roleId=>({userId:id,roleId})),skipDuplicates:true});}if(body.status==='suspended')await tx.authSession.updateMany({where:{userId:id,revokedAt:null},data:{revokedAt:new Date()}});return tx.user.update({where:{id},data:{...(body.displayName!==undefined?{displayName:body.displayName.trim()}:{}),...(body.status!==undefined?{status:body.status}:{})},select:{id:true,email:true,displayName:true,status:true}})});await this.audit.record({actorUserId:req.user!.id,action:'user.updated',entityType:'user',entityId:id,requestId:req.requestId});return{data:user}}
  @Get('roles') @RequirePermissions('roles.read') async roles(){return{data:await this.prisma.role.findMany({orderBy:{name:'asc'},include:{permissions:{include:{permission:true}},_count:{select:{users:true}}}})}}
  @Post('roles') @RequirePermissions('roles.manage') async createRole(@Body()body:{key:string;name:string;permissionIds:string[]},@Req()req:GateviaRequest){if(!/^[a-z][a-z0-9_]+$/.test(body.key))throw new BadRequestException('Role key is invalid.');const role=await this.prisma.role.create({data:{key:body.key,name:body.name,isSystem:false,permissions:{create:body.permissionIds.map(permissionId=>({permissionId}))}},include:{permissions:{include:{permission:true}}}});await this.audit.record({actorUserId:req.user!.id,action:'role.created',entityType:'role',entityId:role.id,requestId:req.requestId});return{data:role}}
  @Patch('roles/:id') @RequirePermissions('roles.manage') async updateRole(@Param('id')id:string,@Body()body:{name?:string;permissionIds?:string[]},@Req()req:GateviaRequest){const current=await this.prisma.role.findUniqueOrThrow({where:{id}});if(current.key==='super_admin')throw new BadRequestException('The Super Admin system role grants cannot be changed.');const role=await this.prisma.$transaction(async(tx)=>{if(body.permissionIds){await tx.rolePermission.deleteMany({where:{roleId:id}});await tx.rolePermission.createMany({data:body.permissionIds.map(permissionId=>({roleId:id,permissionId})),skipDuplicates:true});}return tx.role.update({where:{id},data:{...(body.name!==undefined?{name:body.name.trim()}:{})},include:{permissions:{include:{permission:true}}}})});await this.audit.record({actorUserId:req.user!.id,action:'role.updated',entityType:'role',entityId:id,requestId:req.requestId});return{data:role}}
  @Get('permissions') @RequirePermissions('roles.read') async permissions(){return{data:await this.prisma.permission.findMany({orderBy:{key:'asc'}})}}
}
