/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/admin/audit-logs": {
    get: operations["AuditController_list"];
  };
  "/api/v1/auth/login": {
    post: operations["AuthController_login"];
  };
  "/api/v1/auth/forgot-password": {
    post: operations["AuthController_forgot"];
  };
  "/api/v1/auth/reset-password": {
    post: operations["AuthController_reset"];
  };
  "/api/v1/auth/refresh": {
    post: operations["AuthController_refresh"];
  };
  "/api/v1/auth/logout": {
    post: operations["AuthController_logout"];
  };
  "/api/v1/auth/me": {
    get: operations["AuthController_me"];
  };
  "/api/v1/health/live": {
    get: operations["HealthController_live"];
  };
  "/api/v1/health/ready": {
    get: operations["HealthController_ready"];
  };
  "/api/v1/public/forms/contact": {
    post: operations["PublicFormsController_contact"];
  };
  "/api/v1/public/forms/consultation": {
    post: operations["PublicFormsController_consultation"];
  };
  "/api/v1/public/forms/market-entry-assessment": {
    post: operations["PublicFormsController_assessment"];
  };
  "/api/v1/admin/leads": {
    get: operations["AdminLeadsController_list"];
  };
  "/api/v1/admin/leads/{id}": {
    get: operations["AdminLeadsController_detail"];
  };
  "/api/v1/admin/leads/{id}/status": {
    patch: operations["AdminLeadsController_status"];
  };
  "/api/v1/admin/leads/{id}/assignee": {
    patch: operations["AdminLeadsController_assign"];
  };
  "/api/v1/admin/leads/{id}/notes": {
    post: operations["AdminLeadsController_note"];
  };
  "/api/v1/admin/leads/{id}/activities": {
    get: operations["AdminLeadsController_activities"];
  };
  "/api/v1/admin/languages": {
    get: operations["LanguagesController_list"];
    post: operations["LanguagesController_create"];
  };
  "/api/v1/admin/languages/{id}": {
    patch: operations["LanguagesController_update"];
  };
  "/api/v1/admin/languages/{id}/activate": {
    post: operations["LanguagesController_activate"];
  };
  "/api/v1/admin/languages/{id}/deactivate": {
    post: operations["LanguagesController_deactivate"];
  };
  "/api/v1/admin/languages/{id}/set-default": {
    post: operations["LanguagesController_setDefault"];
  };
  "/api/v1/admin/media": {
    get: operations["MediaController_list"];
  };
  "/api/v1/admin/media/upload-session": {
    post: operations["MediaController_session"];
  };
  "/api/v1/admin/media/{id}/replace-session": {
    post: operations["MediaController_replaceSession"];
  };
  "/api/v1/admin/media/finalize": {
    post: operations["MediaController_finalize"];
  };
  "/api/v1/admin/media/{id}": {
    patch: operations["MediaController_update"];
  };
  "/api/v1/admin/media/{id}/usages": {
    get: operations["MediaController_usages"];
  };
  "/api/v1/admin/media/{id}/archive": {
    post: operations["MediaController_archive"];
  };
  "/api/v1/admin/media/{id}/retry": {
    post: operations["MediaController_retry"];
  };
  "/api/v1/admin/media-folders": {
    get: operations["MediaController_folders"];
    post: operations["MediaController_createFolder"];
  };
  "/api/v1/admin/media-folders/{id}": {
    patch: operations["MediaController_updateFolder"];
  };
  "/api/v1/admin/users": {
    get: operations["IdentityController_users"];
    post: operations["IdentityController_createUser"];
  };
  "/api/v1/admin/users/{id}": {
    get: operations["IdentityController_getUser"];
    patch: operations["IdentityController_updateUser"];
  };
  "/api/v1/admin/roles": {
    get: operations["IdentityController_roles"];
    post: operations["IdentityController_createRole"];
  };
  "/api/v1/admin/roles/{id}": {
    patch: operations["IdentityController_updateRole"];
  };
  "/api/v1/admin/permissions": {
    get: operations["IdentityController_permissions"];
  };
  "/api/v1/admin/{resource}": {
    get: operations["AdminContentController_list"];
    post: operations["AdminContentController_create"];
  };
  "/api/v1/admin/{resource}/{id}": {
    get: operations["AdminContentController_detail"];
    patch: operations["AdminContentController_update"];
  };
  "/api/v1/admin/{resource}/{id}/publish": {
    post: operations["AdminContentController_publish"];
  };
  "/api/v1/admin/{resource}/{id}/unpublish": {
    post: operations["AdminContentController_unpublish"];
  };
  "/api/v1/admin/{resource}/{id}/archive": {
    post: operations["AdminContentController_archive"];
  };
  "/api/v1/admin/{resource}/{id}/preview": {
    post: operations["AdminContentController_preview"];
  };
  "/api/v1/public/languages": {
    get: operations["PublicContentController_languages"];
  };
  "/api/v1/public/settings": {
    get: operations["PublicContentController_settings"];
  };
  "/api/v1/public/navigation/{key}": {
    get: operations["PublicContentController_navigation"];
  };
  "/api/v1/public/redirect": {
    get: operations["PublicContentController_redirect"];
  };
  "/api/v1/public/{resource}": {
    /** Published localized content with filters and pagination */
    get: operations["PublicContentController_list"];
  };
  "/api/v1/public/{resource}/{slug}": {
    get: operations["PublicContentController_detail"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AuditController_list: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_login: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_forgot: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_reset: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_refresh: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_logout: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_me: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  HealthController_live: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  HealthController_ready: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PublicFormsController_contact: {
    parameters: {
      header: {
        "Idempotency-Key": string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PublicFormsController_consultation: {
    parameters: {
      header: {
        "Idempotency-Key": string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PublicFormsController_assessment: {
    parameters: {
      header: {
        "Idempotency-Key": string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminLeadsController_list: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminLeadsController_detail: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminLeadsController_status: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminLeadsController_assign: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminLeadsController_note: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminLeadsController_activities: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  LanguagesController_list: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  LanguagesController_create: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  LanguagesController_update: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  LanguagesController_activate: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  LanguagesController_deactivate: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  LanguagesController_setDefault: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  MediaController_list: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  MediaController_session: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  MediaController_replaceSession: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  MediaController_finalize: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  MediaController_update: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  MediaController_usages: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  MediaController_archive: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  MediaController_retry: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  MediaController_folders: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  MediaController_createFolder: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  MediaController_updateFolder: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  IdentityController_users: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  IdentityController_createUser: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  IdentityController_getUser: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  IdentityController_updateUser: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  IdentityController_roles: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  IdentityController_createRole: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  IdentityController_updateRole: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  IdentityController_permissions: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminContentController_list: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminContentController_create: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminContentController_detail: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminContentController_update: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminContentController_publish: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminContentController_unpublish: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminContentController_archive: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminContentController_preview: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  PublicContentController_languages: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PublicContentController_settings: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PublicContentController_navigation: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PublicContentController_redirect: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Published localized content with filters and pagination */
  PublicContentController_list: {
    parameters: {
      query: {
        locale: unknown;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PublicContentController_detail: {
    parameters: {
      query: {
        locale: unknown;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
}
